### 1. Load Necessary Libraries and Data:

In [1]:
# import pandas as pd
# from sklearn.preprocessing import StandardScaler
# from sklearn.metrics import mean_squared_error
# from joblib import load  # Assuming your TPOT pipeline is saved in a joblib file

# # Load the existing data
# existing_data = pd.read_csv('your_existing_data.csv')  # Replace with the actual path to your data

# # Load the updated data (every 2 weeks)
# updated_data = pd.read_csv('your_updated_data.csv')  # Replace with the actual path to your data

### 2. Standardize Features:

In [2]:
# # Assuming 'Date' is the index, if not, set it as the index
# existing_data.set_index('Date', inplace=True)
# updated_data.set_index('Date', inplace=True)

# # Extract features for both datasets
# X_existing = existing_data[['Year', 'tavg', 'tmin', 'tmax', 'prcp', 'Month_August', 'Month_December', 'Month_February', 'Month_January',
#        'Month_July', 'Month_June', 'Month_March', 'Month_May',
#        'Month_November', 'Month_October', 'Month_September']]

# X_updated = updated_data[['Year', 'tavg', 'tmin', 'tmax', 'prcp', 'Month_August', 'Month_December', 'Month_February', 'Month_January',
#        'Month_July', 'Month_June', 'Month_March', 'Month_May',
#        'Month_November', 'Month_October', 'Month_September']]

# # Standardize the features
# scaler = StandardScaler()
# X_existing_scaled = scaler.fit_transform(X_existing)
# X_updated_scaled = scaler.transform(X_updated)

### 3. Make Predictions Using Exported Pipelines:

In [3]:
# # Load the exported pipelines for each dependent variable


# exec(open('tpot_hydro_gen_pipeline.py').read())
# exec(open('tpot_solar_gen_pipeline.py').read())
# exec(open('tpot_thermal_gen_pipeline.py').read())
# exec(open('tpot_wind_gen_pipeline.py').read())

# # Make predictions for each dependent variable
# y_pred_hydro = pipeline.predict(X_updated_scaled)
# y_pred_solar = pipeline.predict(X_updated_scaled)
# y_pred_thermal = pipeline.predict(X_updated_scaled)
# y_pred_wind = pipeline.predict(X_updated_scaled)

### 4. Evaluate Predictions:

In [4]:
# # You can evaluate the predictions if you have the true values (y_updated_true) for each dependent variable
# y_updated_true_hydro = updated_data['hydro_generation_(mw)']
# y_updated_true_solar = updated_data['solar_generation_(mu)']
# y_updated_true_thermal = updated_data['thermal_lignite_gas,naptha&diesel_generation(mw)']
# y_updated_true_wind = updated_data['wind_generation_(mu)']

# # Evaluate the predictions
# mse_hydro = mean_squared_error(y_updated_true_hydro, y_pred_hydro)
# mse_solar = mean_squared_error(y_updated_true_solar, y_pred_solar)
# mse_thermal = mean_squared_error(y_updated_true_thermal, y_pred_thermal)
# mse_wind = mean_squared_error(y_updated_true_wind, y_pred_wind)

# print(f'Mean Squared Error for hydro_generation_(mw): {mse_hydro}')
# print(f'Mean Squared Error for solar_generation_(mu): {mse_solar}')
# print(f'Mean Squared Error for thermal_lignite_gas,naptha&diesel_generation(mw): {mse_thermal}')
# print(f'Mean Squared Error for wind_generation_(mu): {mse_wind}')

#### With existing dataset

In [5]:
import pandas as pd

In [6]:

existing_data1 = pd.read_csv(r"E:\data_analytics\ISB AMPBA CoW23\Training material\0. ISB Tutotrials\6. Term-5\FP-2\Dataset\web scrapping\generation4_data.csv")

In [7]:
existing_data1 = existing_data1.drop(["index"],axis=1)

existing_data1.drop_duplicates(inplace=True)

# Create a new DataFrame without duplicates
existing_data1_no_duplicates = existing_data1.drop_duplicates()

In [20]:
existing_data1_no_duplicates

,Date,hydro_generation_(mw),solar_generation_(mu),"thermal_lignite_gas,_naptha_&_diesel_generation_(mw)",wind_generation_(mu),Year,tavg,tmin,tmax,prcp,...,Month_December,Month_February,Month_January,Month_July,Month_June,Month_March,Month_May,Month_November,Month_October,Month_September
0,2018-01-01,203.0,60.08,110.0,60.0,2018,22.2,16.6,28.4,0.0,...,False,False,True,False,False,False,False,False,False,False
1,2018-01-01,203.0,60.08,110.0,60.0,2018,26.2,22.1,30.5,0.0,...,False,False,True,False,False,False,False,False,False,False
8,2018-01-01,203.0,60.08,110.0,60.0,2018,25.1,15.5,31.0,0.0,...,False,False,True,False,False,False,False,False,False,False
12,2018-01-02,209.0,58.10,114.0,49.0,2018,22.1,17.8,28.9,0.0,...,False,False,True,False,False,False,False,False,False,False
13,2018-01-02,209.0,58.10,114.0,49.0,2018,26.2,21.2,31.0,0.0,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20596,2022-07-24,743.0,208.28,94.0,347.0,2022,28.1,25.6,30.4,7.1,...,False,False,False,True,False,False,False,False,False,False
20600,2022-07-25,772.0,221.44,103.0,273.0,2022,24.1,20.2,28.5,0.5,...,False,False,False,True,False,False,False,False,False,False
20601,2022-07-25,772.0,221.44,103.0,273.0,2022,28.1,25.4,32.6,2.9,...,False,False,False,True,False,False,False,False,False,False
20602,2022-07-25,772.0,221.44,103.0,273.0,2022,30.7,26.8,35.7,0.0,...,False,False,False,True,False,False,False,False,False,False
20612,2022-07-25,772.0,221.44,103.0,273.0,2022,28.3,25.1,30.2,7.1,...,False,False,False,True,False,False,False,False,False,False

In [9]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from joblib import load  # Assuming your TPOT pipeline is saved in a joblib file

# Load the existing data
existing_data = existing_data1_no_duplicates.tail(30)

In [13]:
existing_data = existing_data.reset_index()

In [14]:
# Assuming 'Date' is the index, if not, set it as the index
existing_data.set_index('Date', inplace=True)

# Extract features for both datasets
X_existing = existing_data[['Year', 'tavg', 'tmin', 'tmax', 'prcp', 'Month_August', 'Month_December', 'Month_February', 'Month_January',
       'Month_July', 'Month_June', 'Month_March', 'Month_May',
       'Month_November', 'Month_October', 'Month_September']]


# Standardize the features
scaler = StandardScaler()
X_existing_scaled = scaler.fit_transform(X_existing)

In [15]:
import joblib

tpot_hydro_gen_model = joblib.load('E:/data_analytics/ISB AMPBA CoW23/Training material/0. ISB Tutotrials/6. Term-5/FP-2/tpot_outputs/tpot_hydro_gen_model.pkl')
tpot_solar_gen_model = joblib.load('E:/data_analytics/ISB AMPBA CoW23/Training material/0. ISB Tutotrials/6. Term-5/FP-2/tpot_outputs/tpot_solar_gen_model.pkl')
tpot_thermal_gen_model = joblib.load('E:/data_analytics/ISB AMPBA CoW23/Training material/0. ISB Tutotrials/6. Term-5/FP-2/tpot_outputs/tpot_thermal_gen_model.pkl')
tpot_wind_gen_model = joblib.load('E:/data_analytics/ISB AMPBA CoW23/Training material/0. ISB Tutotrials/6. Term-5/FP-2/tpot_outputs/tpot_wind_gen_model.pkl')


# # Make predictions for each dependent variable
y_pred_hydro = tpot_hydro_gen_model.predict(X_existing_scaled)
y_pred_solar = tpot_solar_gen_model.predict(X_existing_scaled)
y_pred_thermal = tpot_thermal_gen_model.predict(X_existing_scaled)
y_pred_wind = tpot_wind_gen_model.predict(X_existing_scaled)

In [21]:
y_pred_hydro.mean()

355.3339787201709

In [16]:
existing_data.columns

Index(['index', 'hydro_generation_(mw)', 'solar_generation_(mu)',
       'thermal_lignite_gas,_naptha_&_diesel_generation_(mw)',
       'wind_generation_(mu)', 'Year', 'tavg', 'tmin', 'tmax', 'prcp',
       'Month_August', 'Month_December', 'Month_February', 'Month_January',
       'Month_July', 'Month_June', 'Month_March', 'Month_May',
       'Month_November', 'Month_October', 'Month_September'],
      dtype='object')

In [17]:
y_true_hydro = existing_data["hydro_generation_(mw)"]
y_true_solar = existing_data['solar_generation_(mu)']
y_true_thermal = existing_data['thermal_lignite_gas,_naptha_&_diesel_generation_(mw)']
y_true_wind = existing_data['wind_generation_(mu)']

In [18]:
# Evaluate the predictions
mse_hydro = mean_squared_error(y_true_hydro, y_pred_hydro)
mse_solar = mean_squared_error(y_true_solar, y_pred_solar)
mse_thermal = mean_squared_error(y_true_thermal, y_pred_thermal)
mse_wind = mean_squared_error(y_true_wind, y_pred_wind)

print(f'Mean Squared Error for hydro_generation_(mw): {mse_hydro}')
print(f'Mean Squared Error for solar_generation_(mu): {mse_solar}')
print(f'Mean Squared Error for thermal_lignite_gas,naptha&diesel_generation(mw): {mse_thermal}')
print(f'Mean Squared Error for wind_generation_(mu): {mse_wind}')

Mean Squared Error for hydro_generation_(mw): 145155.06851411232
Mean Squared Error for solar_generation_(mu): 5888.572571092884
Mean Squared Error for thermal_lignite_gas,naptha&diesel_generation(mw): 299.8587675187977
Mean Squared Error for wind_generation_(mu): 18319.39654574022